version: '3.3'

services:

  postgres:
    container_name: "aws101-postgres"
    image: postgres
    volumes:
      - blogtrack-postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=aws101
      - POSTGRES_PASSWORD=aws101
      - POSTGRES_DB=aws101

volumes:
  blogtrack-postgres-data:
    driver: local
