version: '3.3'

services:
  postgres:
    container_name: stratospheric-postgres
    image: postgres:11.5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=stratospheric
      - POSTGRES_PASSWORD=stratospheric
      - POSTGRES_DB=stratospheric
  localstack:
    container_name: stratospheric-aws-infrastructure
    image: localstack/localstack:0.12.2
    network_mode: bridge
    ports:
      - 4566:4566
    environment:
      - SERVICES=sqs,sns
      - DEFAULT_REGION=eu-central-1
    volumes:
      - ./init/local-aws-infrastructure.sh:/docker-entrypoint-initaws.d/init.sh
  keycloak:
    image: jboss/keycloak:11.0.0
    ports:
      - 8888:8080
    environment:
      - KEYCLOAK_USER=keycloak
      - KEYCLOAK_PASSWORD=keycloak
      - DB_VENDOR=h2
#      - JAVA_OPTS=-Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/tmp/keycloak-dump.json
#    volumes:
#      - ./init/keycloak-dump.json:/tmp/keycloak-dump.json
