version: '3.3'

services:
  postgres:
    image: postgres:12.9
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=stratospheric
      - POSTGRES_PASSWORD=stratospheric
      - POSTGRES_DB=stratospheric
  localstack:
    image: localstack/localstack:0.12.2
    ports:
      - 4566:4566
    environment:
      - SERVICES=sqs,ses
      - DEFAULT_REGION=eu-central-1
    volumes:
      - ./init/local-aws-infrastructure.sh:/docker-entrypoint-initaws.d/init.sh
  keycloak:
    image: jboss/keycloak:11.0.0
    ports:
      - 8888:8080
    environment:
      - KEYCLOAK_USER=keycloak
      - KEYCLOAK_PASSWORD=keycloak
      - DB_VENDOR=h2
      - JAVA_OPTS=-Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/tmp/stratospheric-realm.json
    volumes:
      - ./init/stratospheric-realm.json:/tmp/stratospheric-realm.json
