spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            clientId: ${COGNITO_CLIENT_ID}
            clientSecret: ${COGNITO_CLIENT_SECRET}
            scope: openid, profile, email
            clientName: stratospheric-users-client
        provider:
          cognito:
            issuerUri: ${COGNITO_PROVIDER_URL}

custom:
  sharing-queue: ${TODO_SHARING_QUEUE_NAME}
  updates-topic: ${TODO_UPDATES_TOPIC_NAME}
