spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            clientId: ${COGNITO_CLIENT_ID}
            clientSecret: ${COGNITO_CLIENT_SECRET}
            scope: openid, profile, email
            clientName: stratospheric-users-client
        provider:
          cognito:
            issuerUri: ${COGNITO_PROVIDER_URL}
custom:
  web-socket-relay-host: ${AMAZON_MQ_ACTIVE_MQ_WEBSOCKET_RELAY_HOST}
  web-socket-relay-port: ${AMAZON_MQ_ACTIVE_MQ_WEBSOCKET_RELAY_PORT}
