spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            clientId: ${COGNITO_CLIENT_ID}
            clientSecret: ${COGNITO_CLIENT_SECRET}
            scope: openid, profile, email
            clientName: stratospheric-users-client
        provider:
          cognito:
            issuerUri: https://cognito-idp.eu-central-1.amazonaws.com/${COGNITO_USER_POOL_ID}
  activemq:
    broker-url: ${AMAZON_MQ_ACTIVE_MQ_BROKER_URL}
    user: ${AMAZON_MQ_ACTIVE_MQ_USER}
    password: ${AMAZON_MQ_ACTIVE_MQ_PASSWORD}
