cloud:
  aws:
    stack:
      auto: false
    region:
      auto: false
      static: eu-central-1

server:
  forward-headers-strategy: framework

custom:
  invitation-codes: DUKE, HELLO_WORLD, AWSDEV101 # TODO: outsource them -> e.g. env variable or database
  security:
    enabled: true
  sharing-queue: aws101-todo-sharing
