name: Feedback for the eBook
description: "Everything related to the eBook: Typos, Layout Issues, Broken Links, Wrong Explanations, etc."
labels: ["ebook-feedback", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to provide feedback to improve the overall quality of Stratospheric!
  - type: textarea
    id: what-happened
    attributes:
      label: "What can we improve?"
      description: "Try to be as specific as possible - for example: On page 47 there's a typo 'Strotospheric'"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: "To which eBook version are you referring to? You can find the version as part of the Changelog (one of the last pages). Pick 'latest' if you can't find it"
    validations:
      required: true
  - type: textarea
    id: suggested-change
    attributes:
      label: Suggested Changes
      description: What would you suggest to change or what do you expect as a reader?

