cloud:
  aws:
    credentials:
      profile-name: stratospheric
    region:
      static: eu-central-1
      auto: false
    stack:
      auto: false # Automatic stack detection

custom:
  bucket-name: stratospheric-demo-bucket # TODO: outsource to SSM
  sqs-queue-name: stratospheric-demo-queue