name: Create a Todo-App-specific environment

on:
  workflow_dispatch:
    inputs:
      environmentName:
        description: 'The name of the environment in which to deploy the Todo-App-specific environment resources.'
        required: true
        default: 'staging'
jobs:
  deploy-messaging-stack:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Deploy the messaging stack
    steps:

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0

      - name: Deploy messaging stack
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          cd cdk
          npm run messaging:deploy -- -c environmentName=${{ github.event.inputs.environmentName }} -c applicationName=todo-app
  deploy-database-stack:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Deploy the database stack
    steps:

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0

      - name: Deploy database stack
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          cd cdk
          npm run database:deploy -- -c environmentName=${{ github.event.inputs.environmentName }} -c applicationName=todo-app
  deploy-cognito-stack:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Deploy the Cognito stack
    steps:

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0

      - name: Deploy Cognito stack
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          cd cdk
          npm run cognito:deploy -- -c environmentName=${{ github.event.inputs.environmentName }} -c applicationName=todo-app
