name: Update Todo-App-specific environment

on:
  push:
    paths:
      - 'cdk/src/main/java/dev/stratospheric/cdk/**Cognito**'
      - 'cdk/src/main/java/dev/stratospheric/cdk/**Database**'
      - 'cdk/src/main/java/dev/stratospheric/cdk/**Messaging**'
jobs:
  deploy-messaging-stack:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Update the messaging stack
    steps:

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0

      - name: Deploy messaging stack
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          cd cdk
          npm run messaging:deploy -- -c environmentName=staging -c applicationName=todo-app
  deploy-database-stack:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Update the database stack
    steps:

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0

      - name: Deploy database stack
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          cd cdk
          npm run database:deploy -- -c environmentName=staging -c applicationName=todo-app
  deploy-cognito-stack:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Update the Cognito stack
    steps:

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0

      - name: Deploy Cognito stack
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          cd cdk
          npm run cognito:deploy -- -c environmentName=staging -c applicationName=todo-app
