name: Build Chapter Versions

on:
  push:
    paths:
      - 'chapters/**'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        chapter-numbers: [ 1, 8, 13 ]
    runs-on: ubuntu-20.04
    name: Build the application for chapter ${{ matrix.chapter-numbers }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0

      - name: Build and destroy the infrastructure
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          if [ -d "chapters/chapter-${{ matrix.chapter-numbers }}/cdk" ]; then
            cd chapters/chapter-${{ matrix.chapter-numbers }}/cdk
            sudo npm install -g aws-cdk
            mvn package
            cdk deploy -c accountId=${AWS_ACCOUNT_ID} -c region=${AWS_DEFAULT_REGION} --require-approval never
            cdk destroy -c accountId=${AWS_ACCOUNT_ID} -c region=${AWS_DEFAULT_REGION} --force --require-approval never
          fi

      - name: Build the application
        run: |
          if [ -d "chapters/chapter-${{ matrix.chapter-numbers }}/application" ]; then
            cd chapters/chapter-${{ matrix.chapter-numbers }}/application
            ./gradlew build --stacktrace
          fi

  build-complex-chapters:
    strategy:
      fail-fast: false
      matrix:
        chapter-numbers: [ 10, 11, 12 ]
    runs-on: ubuntu-20.04
    name: Build the application for chapter ${{ matrix.chapter-numbers }}
    env:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0

      - name: Create the AWS infrastructure
        working-directory: chapters/chapter-${{ matrix.chapter-numbers }}/cdk
        run: |
          npm install
          npm run all:deploy

      - name: Build the application
        working-directory: chapters/chapter-${{ matrix.chapter-numbers }}/application
        run: |
          ./gradlew build --stacktrace
          docker build -t todo-app-${{ matrix.chapter-numbers }} .
          aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

      - name: Destroy the AWS infrastructure
        if: always()
        working-directory: chapters/chapter-${{ matrix.chapter-numbers }}/cdk
        run: |
          npm run all:destroy
