# Simple means that this chapter version doesn't require and entire AWS ECS setup to test
name: Build Simple Chapter Versions

on:
  push:
    paths:
      - 'chapters/chapter-1/**'

jobs:
  build-first-chapter:
    runs-on: ubuntu-20.04
    name: Build the Application for Chapter 1
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0

      - name: Build the application
        working-directory: chapters/chapter-1/application
        run: ./gradlew build --stacktrace
